//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPDF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail code.
        /// </summary>
        internal static string DetailCodeIs {
            get {
                return ResourceManager.GetString("DetailCodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        internal static string ErrorCodeIs {
            get {
                return ResourceManager.GetString("ErrorCodeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating HPDFAnnotation object..
        /// </summary>
        internal static string FailedCreatingAnnotation {
            get {
                return ResourceManager.GetString("FailedCreatingAnnotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating HPDFDestination object..
        /// </summary>
        internal static string FailedCreatingDestination {
            get {
                return ResourceManager.GetString("FailedCreatingDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating HPDFDocument object..
        /// </summary>
        internal static string FailedCreatingDocument {
            get {
                return ResourceManager.GetString("FailedCreatingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating HPDFEncoder object..
        /// </summary>
        internal static string FailedCreatingEncoder {
            get {
                return ResourceManager.GetString("FailedCreatingEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating HPDFFont object..
        /// </summary>
        internal static string FailedCreatingFont {
            get {
                return ResourceManager.GetString("FailedCreatingFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating HPDFImage object..
        /// </summary>
        internal static string FailedCreatingImage {
            get {
                return ResourceManager.GetString("FailedCreatingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating HPDFOutline object..
        /// </summary>
        internal static string FailedCreatingOutline {
            get {
                return ResourceManager.GetString("FailedCreatingOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed creating HPDFPage object..
        /// </summary>
        internal static string FailedCreatingPage {
            get {
                return ResourceManager.GetString("FailedCreatingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library %1 can&apos;t be found..
        /// </summary>
        internal static string LibraryName {
            get {
                return ResourceManager.GetString("LibraryName", resourceCulture);
            }
        }
    }
}
